global:
  scrape_interval:     15s # 默认每15秒采集一次
  external_labels:
    monitor: 'go-micro-monitor'
scrape_configs:
  - job_name: 'order'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9085']
  - job_name: 'xxxx'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
